version: 22.0.3-sl.{build}

image:
- Visual Studio 2017

clone_depth: 1

environment:
  matrix:
    - CefBuildConfig: Release
      BuildConfig: RelWithDebInfo
      ReleaseName: release

    - CefBuildConfig: Debug
      BuildConfig: Debug
      ReleaseName: debug

  CURL_VERSION: 7.56.1
  CmakeGenerator: Visual Studio 15 2017
  DepsPath32: $(APPVEYOR_BUILD_FOLDER)\dependencies2017\win32
  DepsPath64: $(APPVEYOR_BUILD_FOLDER)\dependencies2017\win64
  BuildPath32: $(APPVEYOR_BUILD_FOLDER)\build32
  BuildPath64: $(APPVEYOR_BUILD_FOLDER)\build64
  InstallPath: $(APPVEYOR_BUILD_FOLDER)\packed_build
  CefVersion: 3.3578.1859.g3563564
  CefDirName: cef_binary_$(CefVersion)_windows64
  CefPath: $(APPVEYOR_BUILD_FOLDER)\$(CefDirName)
  CefBuildPath: $(CefPath)\build
  CefZip: $(CefDirName).zip
  CefUrl: https://s3-us-west-2.amazonaws.com/streamlabs-cef-dist/$(CefZip)
  ReleaseArtifact: libobs-$(ReleaseName)-$(APPVEYOR_BUILD_VERSION)-win32-x64.7z
  DependenciesUrl: https://obsproject.com/downloads/dependencies2017.zip

install:
  - git submodule update --init --recursive --jobs 2
  - mkdir "%InstallPath%\deps\w32-pthreads"
  - copy C:\projects\obs-studio\deps\w32-pthreads\pthread.h "%InstallPath%\deps\w32-pthreads" 
  - mkdir "%BuildPath32%"
  - mkdir "%BuildPath64%"

build_script:
  - cmd: CI\win-build.cmd

after_build:
  - 7z a "%ReleaseArtifact%" "%InstallPath%\*"

artifacts:
  - path: $(ReleaseArtifact)
    name: Release Artifact

deploy:
  - provider: S3
    access_key_id:
      secure: C1Qzrf1+tbRDGmnXR6OpXwWuJr33d2JCVwn0KC/V7jw=
    secret_access_key:
      secure: dRSFQBZKAAVvDmZ0DOaoF54189P0b0mFCMSyTwn4eHZVBFdaET8C4Nb6VCJ4kT+a
    bucket: obsstudios3.streamlabs.com
    region: us-west-2
    set_public: true
    artifact: $(ReleaseArtifact)
    on:
      branch: streamlabs

test: off
