name: Clang Format Check

on:
  push:
    paths-ignore: ['**.md']
    branches-ignore: [master]
  pull_request:
    paths-ignore: ['**.md']
    branches-ignore: [master]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install clang format
        run: |
          sudo apt-get install -y clang-format-12

      - name: 'Run clang-format'
        run: |
          ./CI/check-format.sh
          ./CI/check-changes.sh
